import { NextRequest, NextResponse } from 'next/server'
import { auth } from '../../../auth'
import { prisma } from '@engineering-copilot/db'
import { z } from 'zod'

const Schema = z.object({
  reviewId: z.string(),
  format: z.enum(['MARKDOWN', 'PDF', 'JIRA_COMMENT', 'ADO_COMMENT']),
})

/** Build a complete Markdown document from all review sections */
function buildMarkdown(review: any): string {
  const header = `# Engineering Review: ${review.title}

> Generated by Engineering Copilot · ${new Date(review.createdAt).toLocaleDateString()}  
> Provider: ${review.aiProvider} / ${review.aiModel}

---

`

  const sections = review.sections
    .map((s: any) => {
      const content = s.userContent ?? s.aiContent
      const editedNote = s.editedByUser ? '\n> *This section was edited by the engineer.*\n' : ''
      return `## ${String(s.sectionIndex).padStart(2, '0')}. ${s.sectionTitle}\n${editedNote}\n${content}`
    })
    .join('\n\n---\n\n')

  return header + sections
}

export async function POST(req: NextRequest) {
  const session = await auth()
  const body = await req.json()
  const parsed = Schema.safeParse(body)
  if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 })

  const { reviewId, format } = parsed.data

  const review = await prisma.review.findUnique({
    where: { id: reviewId },
    include: { sections: { orderBy: { sectionIndex: 'asc' } } },
  })
  if (!review) return NextResponse.json({ error: 'Not found' }, { status: 404 })
  if (!review.isPublic && review.userId !== session?.user?.id) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  // Log export
  await prisma.reviewExport.create({ data: { reviewId, format } })

  if (format === 'MARKDOWN') {
    return NextResponse.json({ content: buildMarkdown(review) })
  }

  if (format === 'JIRA_COMMENT' || format === 'ADO_COMMENT') {
    // Return Markdown — Jira and ADO both accept Markdown in comments
    return NextResponse.json({ content: buildMarkdown(review) })
  }

  if (format === 'PDF') {
    // PDF generation: in production, use a headless browser or Puppeteer
    // For now, return the Markdown for client-side print-to-PDF
    return NextResponse.json({
      content: buildMarkdown(review),
      note: 'Use browser Print → Save as PDF for now. PDF service coming soon.',
    })
  }

  return NextResponse.json({ error: 'Unknown format' }, { status: 400 })
}
